# Generated by Django 5.2.5 on 2025-08-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('benefits', models.CharField(max_length=5000)),
                ('instructions', models.CharField(max_length=5000)),
                ('video_link', models.CharField(max_length=255)),
            ],
        ),
    ]
