# Generated by Django 5.2.5 on 2025-08-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workouts',
            new_name='Workout',
        ),
    ]
